### ISSUE TITLE
Opening city crashes C:S when IMT & NExt2 enabled together

### ISSUE THREAD

**Issue by cucocreative** [MacSergey/NodeMarkup#221]
**Which IMT are you using?  _Stable, BETA, BETA with Early Access_**

Stable 1.6

**What computer OS are you using? (ex:  Linux (version), MACOS, Windows (version))**

MacOS 10.15

**Describe the bug**

I seem to be having compatibility issues with IMT 1.6 enabled alongside with Network Extensions 2.
- I can load a city from before I used IMT okay with NExt2 enabled.
- I can load a new game with IMT & NExt2 enabled okay
- Any city that has used IMT will crash if IMT & NExt2 enabled, if I disable NExt2 and load the city it just errors continuously and I have to force quit
- If I disable IMT I can load the city that has used IMT okay and save the city as a new save
- But that new save crashes if I then re-enable IMT
Any thoughts

**To Reproduce**
Load a city with IMT & NExt2 enabled, where the city was previously used with IMT 1.5.x

**Additional information**
Add any other relevant information pertaining to the issue goes here.

Last few lines from player.log:

Debug info from gdb:

-----

#23 0x007fff357707d5 in ReceiveNextEventCommon
#24 0x007fff35770579 in _BlockUntilNextEventMatchingListInModeWithFilter
#25 0x007fff33db6039 in _DPSNextEvent
#26 0x007fff33db4880 in -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
#27 0x000001020f4e9e in -[NSApplication(SteamOverrideNextEvent) steamhooked_nextEventMatchingMask:untilDate:inMode:dequeue:]
#28 0x007fff33da658e in -[NSApplication run]
#29 0x007fff33d78396 in NSApplicationMain
#30 0x00000100e5d275 in PlayerMain(int, char const**)
#31 0x00000100001e34 in start

Got a SIGABRT while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

----

Can supply whole player.log and content of Apple crash report if required.

**Comment by MacSergey** [comment]
need full log file

**Comment by cucocreative** [comment]
[Player.log](https://github.com/MacSergey/NodeMarkup/files/6172225/Player.log)
[C-S crash report IMT.txt](https://github.com/MacSergey/NodeMarkup/files/6172226/C-S.crash.report.IMT.txt)

**Comment by MacSergey** [comment]
please try Beta version. I think it was fixed. (unsub from stable before)
https://steamcommunity.com/sharedfiles/filedetails/?id=2159934925

**Comment by cucocreative** [comment]
I did try Beta a couple days back as part of problem solving process - but I'll give it ago again later today as I see it was updated today.

**Comment by cucocreative** [comment]
Tried 1.7.0.191 beta but it still crashes C:S when loading previously saved games that used IMT 1.5.x. New log attached.

Loads a new city I started yesterday fine.

[Player.log](https://github.com/MacSergey/NodeMarkup/files/6173388/Player.log)

**Comment by MacSergey** [comment]
this log not exist loading map

**Comment by cucocreative** [comment]
is this better?

[Player.log](https://github.com/MacSergey/NodeMarkup/files/6174005/Player.log)

**Comment by MacSergey** [comment]
I need more data. I extend log data. 
replace it file in <Steam Folder>\steamapps\workshop\content\255710\2159934925
load map and after send log

[NodeMarkup.zip](https://github.com/MacSergey/NodeMarkup/files/6174127/NodeMarkup.zip)
zip pass: 123

**Comment by MacSergey** [comment]
I think last beta (1.7.0.216) will fix it

**Comment by cucocreative** [comment]
.209 crashed but .216 has worked – yeah! I loaded the city, saved as a new save and then quit and opened the new save okay and although a handful of intersections have lost their markings this issue only seems to have affected a small handful – quickly panning around the city it seems less then 10 need remarking up.

Thanks for looking into this for me, much appreciated. Now I can try. and get my city up to 300k population.

**Comment by MacSergey** [comment]
yeah, .209 only extend log data, nothing fix. Anyway I need log from .209 version to better understand the cause of the error

**Comment by cucocreative** [comment]
this is the log file from .209
[Player.log](https://github.com/MacSergey/NodeMarkup/files/6178190/Player.log)
